sudo: required

services:
  - docker

before_install:
  - docker build -t rossnerr/access-barrier .

script:
#   - docker run rossnerr/access-barrier

# after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rossnerr/access-barrier

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: access-barrier
  env: Accessbarrier-env
  bucket_name: elasticbeanstalk-us-west-2-895923276358
  bucket_path: access-barrier
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
