sudo: required

services:
  - docker

before_install:
  - docker-compose build

script:
#   - docker run rossnerr/access-barrier

# after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  # Tag images
  - docker tag access-barrier-app $DOCKER_ID/access-barrier-app
  - docker tag access-barrier-db $DOCKER_ID/access-barrier-db

  - docker push $DOCKER_ID/access-barrier-app
  - docker push $DOCKER_ID/access-barrier-db

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: DemoApp
  env: Demoapp-env
  bucket_name: elasticbeanstalk-us-west-2-895923276358
  bucket_path: DemoApp
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
