version: '3'

services:
  access-barrier-db:
    image: postgres
    container_name: access-barrier-db
    environment:
      - POSTGRES_DB=access_barrier
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5434:5432

  access-barrier-app:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: access-barrier-app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://access_barrier_db:5432/access_barrier
    ports:
      - 8084:8080
    depends_on:
      - access-barrier-db
